### PR TITLE
ECE651-104 and ECE651-84 order request page for rest owner

### PR DESCRIPTION
**Pull request by kj8patel**
Frontend and Backend changes for Order Requests page (for Restaurant Owner)

Test Results : Documents/General/Sprint 5/Development/ECE651-104

### CODE REVIEW

**Comment by db8patel** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70)
> 
> [Bug](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL) [5 Code Smells](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70) No Coverage information [](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&metric=new_duplicated_lines_density&view=list) [30.3% Duplication](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&metric=new_duplicated_lines_density&view=list)

It has merging conflicts and sonarCloud code analysis is failing.

**Comment by kj8patel** [comment]
> > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70)
> > [Bug](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL) [5 Code Smells](https://sonarcloud.io/project/issues?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&resolved=false&types=CODE_SMELL)
> > [No Coverage information](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70) No Coverage information [](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&metric=new_duplicated_lines_density&view=list) [30.3% Duplication](https://sonarcloud.io/component_measures?id=kar12thik_Online-Food-Ordering-and-Delivery-System&pullRequest=70&metric=new_duplicated_lines_density&view=list)
> 
> It has merging conflicts and sonarCloud code analysis is failing.

Yeah, GitHub and sonarCloud showed it way earlier.

**Comment by kj8patel** [comment]
Update:
SonarCloud issues have been resolved now.

**Comment by kar12thik** [comment]
image

Can we replace the Food, Drinks with restDescription field value from users collection.

**Comment by kj8patel** [comment]
> image
> 
> @kj8patel Can we replace the Food, Drinks with restDescription field value from users collection.

Added in the latest commit.

**Review by kar12thik — APPROVED** [review]
Looks good.

**Comment by kar12thik** [comment]
> image
> 
> @kj8patel Can we replace the Food, Drinks with restDescription field value from users collection.

Also, we should display Restaurant Name instead of Restaurant Owner Name.

**Review by MareenaFr — APPROVED** [review]
Changes looks good.

**Comment by kj8patel** [comment]
> > image
> > @kj8patel Can we replace the Food, Drinks with restDescription field value from users collection.
> 
> Also, we should display Restaurant Name instead of Restaurant Owner Name.

Addressed this in latest commit.

**Review by MareenaFr — APPROVED** [review]

**Review by kar12thik — APPROVED** [review]

**Review by db8patel — APPROVED** [review]

**Pull request merged**
