### PR TITLE
ECE651-52 Register Restaurant Display Form - Frontend

### PR DESCRIPTION
**Pull request by kar12thik**
Code changes for Register Restaurant - Frontend

Test Results Location : Documents/General/Sprint 4/Development/ECE651-52

### CODE REVIEW

**Comment by MareenaFr** [comment]
@kar12thik Do we need Gender and Age fields in Restaurant registration form

**Comment by kar12thik** [comment]
> @kar12thik Do we need Gender and Age fields in Restaurant registration form

Yes, since it's restaurant owner specific details, not about the restaurant.

**Review by MareenaFr — APPROVED** [review]
Changes looks good.

**Comment by kj8patel** [comment]
@kar12thik, in this form, we are just registering the restaurant owner's details, right? So, where are we planning to allow the owner to add related to his/her restaurant?

**Comment by db8patel** [comment]
The fields on the register restaurant page need to be updated, specifically with respect to the following:
1. Full Name replaced by Restaurant Name.
2. Add one more field that asks for the restaurant Owner's Name.
3. We can change the name of Email -> Restaurant E-mail or E-commerce E-mail
**4. Password and Confirm Password is as it is.**
5. We can add the Address before we are asking them for City and Country.
**6. All other parameters should be left as-is.**

The Testing document will need to be revised if these fields are modified.

**Comment by kar12thik** [comment]
> @kar12thik, in this form, we are just registering the restaurant owner's details, right? So, where are we planning to allow the owner to add related to his/her restaurant?

That's the order-requests page which the restaurant owner will be redirected to on login. order-requests by itself is a separate component which will be done in the next sprint

**Comment by kj8patel** [comment]
> The fields on the register restaurant page need to be updated, specifically with respect to the following:
> 
> 1. Full Name replaced by Restaurant Name.
> 2. Add one more field that asks for the restaurant Owner's Name.
> 3. We can change the name of Email -> Restaurant E-mail or E-commerce E-mail
>    **4. Password and Confirm Password is as it is.**
> 4. We can add the Address before we are asking them for City and Country.
>    **6. All other parameters should be left as-is.**
> 
> The Testing document will need to be revised if these fields are modified.

Yeah, I agree with this.

**Comment by kar12thik** [comment]
> The fields on the register restaurant page need to be updated, specifically with respect to the following:
> 
> 1. Full Name replaced by Restaurant Name.
> 2. Add one more field that asks for the restaurant Owner's Name.
> 3. We can change the name of Email -> Restaurant E-mail or E-commerce E-mail
>    **4. Password and Confirm Password is as it is.**
> 4. We can add the Address before we are asking them for City and Country.
>    **6. All other parameters should be left as-is.**
> 
> The Testing document will need to be revised if these fields are modified.

The changes were based on the schema that was initially created and approved by the team. Adding new fields is a new requirement, for which we need to revisit the schema and update with the necessary fields. We'll have to create a new story for schema to address the changes for Register Restaurant. If we proceed to change schema, this current story will be put on hold unless schema story is accepted. Changing label names will not be an issue with the current form. @itsmejay80 @db8patel @kj8patel

**Comment by itsmejay80** [comment]
> 



> > The fields on the register restaurant page need to be updated, specifically with respect to the following:
> > 
> > 1. Full Name replaced by Restaurant Name.
> > 2. Add one more field that asks for the restaurant Owner's Name.
> > 3. We can change the name of Email -> Restaurant E-mail or E-commerce E-mail
> >    **4. Password and Confirm Password is as it is.**
> > 4. We can add the Address before we are asking them for City and Country.
> >    **6. All other parameters should be left as-is.**
> > 
> > The Testing document will need to be revised if these fields are modified.
> 
> The changes were based on the schema that was initially created and approved by the team. Adding new fields is a new requirement, for which we need to revisit the schema and update with the necessary fields. We'll have to create a new story for schema to address the changes for Register Restaurant. If we proceed to change schema, this current story will be put on hold unless schema story is accepted. Changing label names will not be an issue with the current form. @itsmejay80 @db8patel @kj8patel

I will create a new ticket(or bug) for schema changes. We can put this task on hold and start working on the schema task.

**Comment by kar12thik** [comment]
> I will create a new ticket(or bug) for schema changes. We can put this task on hold and start working on the schema task.

It will not be a bug, since it's a requirement change. You can create new story and assign to person having bandwidth to work on schema task. I'll close the open PR's for Register Restaurant.

**Pull request closed without merging**
