### PR TITLE
Story/ece651 103 user sign in using google

### PR DESCRIPTION
**Pull request by db8patel**
Test Plan Document : https://uofwaterloo.sharepoint.com/:f:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/[ECE651-103](https://uofwaterloo.sharepoint.com/:f:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-103?csf=1&web=1&e=1s2rrE)?csf=1&web=1&e=1s2rrE

### CODE REVIEW

**Comment by MareenaFr** [comment]
@db8patel 
Are we implementing Forgot password functionality as well?

image

**Comment by db8patel** [comment]
> @db8patel Are we implementing Forgot password functionality as well?
> 
> image

I have added that because of future enhancement and complete design of login page. We can remove it if we want.

**Review by MareenaFr — DISMISSED** [review]
Changes looks good.

**Review by kar12thik — APPROVED** [review]
Looks good.

**Review by MareenaFr — APPROVED** [review]

**Review by kj8patel — APPROVED** [review]

**Pull request merged**
