### PR TITLE
Story/ece 651 73 user redirection

### PR DESCRIPTION
**Pull request by db8patel**
Test Plan Document : https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%204/Development/ECE651-73/[ECE651-73-User-Redirection-Based-on-Role.xlsx](https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%204/Development/ECE651-73/ECE651-73-User-Redirection-Based-on-Role.xlsx?d=wb4d25230e0bd48beb551e733e25aa674&csf=1&web=1&e=dknc2R)?d=wb4d25230e0bd48beb551e733e25aa674&csf=1&web=1&e=dknc2R

### CODE REVIEW

**Comment by kar12thik** [comment]
@db8patel Conflicts shown for Login.js file.

**Review by MareenaFr — COMMENTED** [review]
image

@db8patel 
LOGIN/REGISTER and REGISTER RESTAURANT links in Navigation bar is misplaced.

**Comment by db8patel** [comment]
> image
> 
> @db8patel LOGIN/REGISTER and REGISTER RESTAURANT links in the Navigation bar is misplaced.

I did that because in every websites navbar, It is on the right end of the screen.

**Comment by kar12thik** [comment]
> > image
> > @db8patel LOGIN/REGISTER and REGISTER RESTAURANT links in the Navigation bar is misplaced.
> 
> I did that because in every websites navbar, It is on the right end of the screen.

Let's keep Register Restaurant to the last, since that's the last button user would want to click.

**Comment by db8patel** [comment]
> > > image
> > > @db8patel LOGIN/REGISTER and REGISTER RESTAURANT links in the Navigation bar is misplaced.
> > 
> > 
> > I did that because in every websites navbar, It is on the right end of the screen.
> 
> Let's keep Register Restaurant to the last, since that's the last button user would want to click.

Done

**Comment by db8patel** [comment]
> @db8patel Build needs to be fixed as well. @MareenaFr @itsmejay80 Issue seems to be in the system test cases.

Yes, I already talked with @MareenaFr yesterday about why it is happening.

**Review by kar12thik — APPROVED** [review]

**Comment by MareenaFr** [comment]
> @db8patel Build needs to be fixed as well. @MareenaFr @itsmejay80 Issue seems to be in the system test cases.

Fixed now. Modified the test cases for Login and Signup.

**Review by Riya0001 — APPROVED** [review]
Looks Good to me

**Review by MareenaFr — APPROVED** [review]

**Pull request merged**
