### PR TITLE
Bugfix/ece651 95 signup form bug fix

### PR DESCRIPTION
**Pull request by db8patel**
Test Plan Document : https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/[ECE651-95-Signup-Form-Bug-Fix.xlsx](https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/ECE651-95-Signup-Form-Bug-Fix.xlsx?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g)?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g

### CODE REVIEW

**Comment by db8patel** [comment]
> Please examine the test plan document to see which problems have been resolved.

 Test Plan Document : [https://uofwaterloo.sharepoint.com/❌/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/[ECE651-95-Signup-Form-Bug-Fix.xlsx](https://uofwaterloo.sharepoint.com/❌/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/ECE651-95-Signup-Form-Bug-Fix.xlsx?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g)?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g](https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/%5BECE651-95-Signup-Form-Bug-Fix.xlsx%5D(https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/Shared%20Documents/General/Sprint%205/Development/ECE651-95/ECE651-95-Signup-Form-Bug-Fix.xlsx?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g)?d=w98c192cfc0f64a78a2d23ec8bb5787ab&csf=1&web=1&e=3xGW2g)

**Review by MareenaFr — DISMISSED** [review]
Changes looks good.

**Comment by kar12thik** [comment]
@db8patel On Signup, when user clicks on login, dialog box doesn't close and it takes me back to Homepage. If user selects to login, dialog box should close instantly and open the login page. Can you check once.

**Comment by db8patel** [comment]
> @db8patel On Signup, when user clicks on login, dialog box doesn't close and it takes me back to Homepage. If user selects to login, dialog box should close instantly and open the login page. Can you check once.

@kar12thik Done.

**Review by MareenaFr — COMMENTED** [review]
@db8patel 
After logging in, if we are navigating to any other page and click LOGOUT button, it's staying on the same page and not navigating to homepage. Can you please check this.

**Review by kar12thik — APPROVED** [review]

**Review by MareenaFr — APPROVED** [review]

**Pull request merged**
