### PR TITLE
ECE651-77 Banner Sub-component Fix

### PR DESCRIPTION
**Pull request by MareenaFr**
Removed Banner component from Home page

Test results location - Documents/General/Sprint 4/Development/ECE651-77

### CODE REVIEW

**Comment by kar12thik** [comment]
@MareenaFr  we might to remove the test cases referencing to Banner component from homescreen.test.js file.

**Comment by MareenaFr** [comment]
> @MareenaFr we might to remove the test cases referring Banner component from homescreen.test.js file.

Removed the test case from homescreen.test.js file

**Review by kar12thik — APPROVED** [review]
Changes look good.

**Review by db8patel — APPROVED** [review]
This looks great! I tested the changes and they work as expected.

**Review by kj8patel — APPROVED** [review]

**Pull request merged**
