### PR TITLE
story/ECE651-76-Change-Display-Logo: Added new icon

### PR DESCRIPTION
**Pull request by itsmejay80**
- Changed Display logo
- Updated Logo:
update
- Unit Test Document : https://uofwaterloo.sharepoint.com/:x:/r/sites/tm-eng-onlinefoodorderinganddeliverysystem/_layouts/15/Doc.aspx?sourcedoc=%7BE95CCC49-420A-48A8-96B1-0839A7A8FEA1%7D&file=Unit_Test_Document_ECE651-73.xlsx&action=default&mobileredirect=true

### CODE REVIEW

**Comment by db8patel** [comment]
The branch name and pull request name have different story numbers (73 and 76).

**Comment by itsmejay80** [comment]
> @itsmejay80 The branch name and pull request name have different story numbers (73 and 76).

Fixed

**Comment by kj8patel** [comment]
> It can not be seen. Viewers may notice something in blue there, but it is not as obvious as a delivery guy driving a scooter. What do you think? image

Maybe in dark mode, it is not visible properly. Otherwise it is clearly visible.
image

**Comment by itsmejay80** [comment]
> It can not be seen. Viewers may notice something in blue there, but it is not as obvious as a delivery guy driving a scooter. What do you think? image

right now we are not focusing on dark mode.

**Review by MareenaFr — APPROVED** [review]

**Comment by kar12thik** [comment]
> > It can not be seen. Viewers may notice something in blue there, but it is not as obvious as a delivery guy driving a scooter. What do you think? image
> 
> right now we are not focusing on dark mode.

For light-mode, this should be good.

**Review by kar12thik — APPROVED** [review]

**Review by db8patel — APPROVED** [review]

**Pull request merged**
