### PR TITLE
Story/ECE651-74 search box redirection

### PR DESCRIPTION
**Pull request by kj8patel**
Added restaurant search box functionality in home page and restaurant lister page.

Test document location: Documents/General/Sprint 5/Development/ECE651-74

### CODE REVIEW

**Comment by kar12thik** [comment]
image

Can we change this to display Restaurant Name, currently it is displaying restaurant owner name. @kj8patel

**Comment by kj8patel** [comment]
> image
> 
> Can we change this to display Restaurant Name, currently it is displaying restaurant owner name. @kj8patel

Right now, I have displayed owner name (userName) because we don't have restaurant name (restName field) in every database entry and as a result, it is giving error while filtering the undefined value (as restName field is not present) while filtering the restaurants. 

Once we have all the data with proper fields, I will change it to restName.

**Comment by kar12thik** [comment]
> > image
> > Can we change this to display Restaurant Name, currently it is displaying restaurant owner name. @kj8patel
> 
> Right now, I have displayed owner name (userName) because we don't have restaurant name (restName field) in every database entry and as a result, it is giving error while filtering the undefined value (as restName field is not present) while filtering the restaurants.
> 
> Once we have all the data with proper fields, I will change it to restName.

I have removed all invalid documents. You should be able to query them without error now using restName field.

**Comment by kj8patel** [comment]
> > > image
> > > Can we change this to display Restaurant Name, currently it is displaying restaurant owner name. @kj8patel
> > 
> > 
> > Right now, I have displayed owner name (userName) because we don't have restaurant name (restName field) in every database entry and as a result, it is giving error while filtering the undefined value (as restName field is not present) while filtering the restaurants.
> > Once we have all the data with proper fields, I will change it to restName.
> 
> I have removed all invalid documents. You should be able to query them without error now using restName field.

Thanks @kar12thik, now you can see rest name displaying after the latest push.

**Review by kar12thik — APPROVED** [review]
Changed look good.

**Review by MareenaFr — APPROVED** [review]
Looks good.

**Review by db8patel — APPROVED** [review]

**Pull request merged**
